version: '2'
services:
  data:
      image: busybox
      volumes:
        - ../www:/data/www # 站点根目录
  nginx:
      restart: always # 设置自启动
      image: ikerlin/nginx:1.10.3-alpine
      ports: # 宿主端口（映射到）-》docker镜像端口
        - "80:80" 
        - "443:443"
      volumes_from:
        - data
      volumes: # 配置文件宿主文件（映射到）-》docker镜像文件
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf #nginx配置
        - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params #fastcgi配置
        - ./nginx/sites-enabled:/etc/nginx/sites-enabled #站点配置
        - ./nginx/certs:/etc/nginx/certs #ssl证书
        - ./nginx/logrotate.d:/etc/logrotate.d/ # 日志分割配置
        - ../log/nginx:/data/log #nginx log目录
      links:
        - "php71"
      # external_links:
      container_name: nginx # docker镜像名称
  # php56:
  #     restart: always #设置自启动
  #     image: ikerlin/php:5.6-fpm
  #     volumes_from:
  #       - data
  #     volumes:
  #       - ../log/php56:/opt/log/php #php log目录
  #     container_name: php56
  php71:
      restart: always #设置自启动
      image: ikerlin/php:7.1-fpm-dev
      volumes_from:
        - data
      volumes:
        - ./php71/base.ini:/usr/local/etc/php/conf.d/base.ini
        - ./php71/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      container_name: php71
  mysql:
      restart: always #设置自启动
      image: mysql:5.7
      ports:
        - "3306:3306"
      volumes:
        - ../mysqlData:/var/lib/mysql #数据目录
        - ./mysql/my.cnf:/etc/mysql/my.cnf  #配置文件
      environment:
        MYSQL_ROOT_PASSWORD: kerlin
      container_name: mysql
  redis:
      restart: always #设置自启动
      image: redis:3.2.8-alpine #本地镜像
      volumes:
        - ../redis:/data #redis持久存储目录
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf #配置文件
      ports:
        - "6379:6379"
      command: redis-server /usr/local/etc/redis/redis.conf #redis持久存储
      container_name: redis